import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Portfolio | Yasindu Nethmina - Frontend Web Developer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className="flex items-center relative bottom-10 w-full">
            <div className="w-7/12">
              <h4 className="text-[#878a8f] tracking-widest leading-4">
                YASINDU NETHMINA
              </h4>
              <h1 className="font-extrabold text-[#0f141e] text-6xl">
                Website and user <br /> interface designer
              </h1>
              <h6 className="font-semibold text-[#878a8f]">
                Over the past 9 years, as an art director and designer, I’ve
                worked with big companies and up-and-coming startups to
                successfully help them reach their full potential and attract
                new customers.
              </h6>
              <div className="flex items-center">
                <button className="font-bold text-sm hover:underline decoration-2 transition-all ease-in-out duration-300 delay-300 underline-offset-4 decoration-[#878a8f] text-[#0f141e]">
                  View Projects
                </button>
                <h6 className="font-semibold text-[#878a8f] mx-4">or</h6>
                <button className="font-bold text-sm hover:underline decoration-2 transition-all ease-in-out duration-300 delay-300 underline-offset-4 decoration-[#878a8f] text-[#0f141e">
                  Read About Me
                </button>
              </div>
            </div>
            <div className="">
              {/* <img
                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK5q0FP74VV9wbfwP378_7kj7iDomHuKrxkXsxDdUT28V9dlVMNUe-EMzaLwaFhneeuZI&usqp=CAU"
                alt="google"
              /> */}
            </div>
          </div>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </Layout>
  );
}
